// Gerado por 06_Scripts/gerar_sessoes_tec.py - NAO editar a mao.
window.SESSOES_TEC = {
 "gerado_em": "2026-09-10T08:14:42",
 "fonte": "07_TEC/TEC_Captura/tec_registros_*.json (1 sessão por dia+assunto) + resultado_simulado_*.json (1 sessão por simulado+dia+matéria)",
 "sessoes": [
  {
   "uid": "TEC~2026-09-02~atos-e-fatos-contabeis-ecc057",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Atos e Fatos Contábeis",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~balancete-de-verificacao-c4c26a",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Balancete de Verificação",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~classificacao-e-subsistemas-do-sfn-75036b",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Classificação e Subsistemas do SFN",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~composicao-geral-do-sfn-294b51",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Composição Geral do SFN",
   "minutos": 1,
   "qResolvidas": 3,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~contribuicoes-de-melhoria-cf-1988-e-ctn-59a33e",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "TRIB",
   "topicId": null,
   "assuntoLivre": "Contribuições de Melhoria (CF/1988 e CTN)",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~demais-temas-sobre-custos-no-setor-publico-6ab4a8",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Demais Temas sobre Custos no Setor Público",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~disposicoes-gerais-do-credito-tributario-arts-139-a-141-do-c-49aed3",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "TRIB",
   "topicId": null,
   "assuntoLivre": "Disposições Gerais do Crédito Tributário (arts. 139 a 141 do CTN)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~disposicoes-gerais-sobre-obrigacao-tributaria-conceito-obrig-2f17ce",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "TRIB",
   "topicId": null,
   "assuntoLivre": "Disposições Gerais sobre Obrigação Tributária (Conceito, Obrigação Principal e Acessória)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~divida-publica-nfsp-e-tipos-de-deficit-publico-no-brasil-96e24d",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Dívida Pública, NFSP e Tipos de Déficit Público no Brasil",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~escrituracao-normas-livros-contabeis-lancamentos-metodo-das--2a030a",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Escrituração: Normas, Livros Contábeis, Lançamentos, Método das Partidas Dobradas",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~extincao-do-credito-tributario-arts-156-a-174-do-ctn-d80ece",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "TRIB",
   "topicId": null,
   "assuntoLivre": "Extinção do Crédito Tributário (arts. 156 a 174 do CTN)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~fato-gerador-arts-114-a-118-do-ctn-91ed1b",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "TRIB",
   "topicId": null,
   "assuntoLivre": "Fato Gerador (arts. 114 a 118 do CTN)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~imunidades-tributarias-5955b6",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "TRIB",
   "topicId": null,
   "assuntoLivre": "Imunidades Tributárias",
   "minutos": 3,
   "qResolvidas": 4,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~lancamento-e-constituicao-do-credito-tributario-arts-142-a-1-7ccde8",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "TRIB",
   "topicId": null,
   "assuntoLivre": "Lançamento e Constituição do Crédito Tributário (arts. 142 a 150 do CTN)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~lei-n-8-137-1990-crimes-contra-a-ordem-tributaria-economica--305309",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "PENAL",
   "topicId": null,
   "assuntoLivre": "Lei nº 8.137/1990 - Crimes contra a Ordem Tributária, Econômica e Relações de Consumo",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~nbc-t-16-11-e-mic-1-edicao-sistema-de-informacao-de-custos-d-d17b7b",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "NBC T 16.11 e MIC 1ª Edição - Sistema de Informação de Custos do Setor Público",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~nbc-tsp-34-custos-no-setor-publico-37edb2",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "NBC TSP 34 - Custos no Setor Público",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~oferta-de-moeda-e-agregados-monetarios-32f613",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Oferta de Moeda e Agregados Monetários",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~plano-de-contas-aefff9",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "CG",
   "topicId": null,
   "assuntoLivre": "Plano de Contas",
   "minutos": 4,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~regimes-cambiais-33acdf",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Regimes Cambiais",
   "minutos": 3,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~solidariedade-arts-124-e-125-do-ctn-041896",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "TRIB",
   "topicId": null,
   "assuntoLivre": "Solidariedade (arts. 124 e 125 do CTN)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~sujeito-ativo-e-passivo-arts-119-a-123-do-ctn-80d551",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "TRIB",
   "topicId": null,
   "assuntoLivre": "Sujeito: Ativo e Passivo (arts. 119 a 123 do CTN)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~suspensao-da-exigibilidade-do-credito-tributario-arts-151-a--84529a",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "TRIB",
   "topicId": null,
   "assuntoLivre": "Suspensão da Exigibilidade do Crédito Tributário (arts. 151 a 155-A do CTN)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~taxa-interna-de-retorno-tir-e-taxa-minima-de-atratividade-tm-f3ed09",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Taxa Interna de Retorno (TIR) e Taxa Mínima de Atratividade (TMA)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~taxas-cf-1988-e-ctn-e7e6ca",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "TRIB",
   "topicId": null,
   "assuntoLivre": "Taxas (CF/1988 e CTN)",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~valor-presente-liquido-vpl-ca8cf8",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Valor Presente Líquido (VPL)",
   "minutos": 1,
   "qResolvidas": 3,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~62",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DEV",
   "topicId": "62",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~amostragem-de-conglomerados-5a6ae8",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "Estat",
   "topicId": null,
   "assuntoLivre": "Amostragem de Conglomerados",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~amostragem-estratificada-c57c21",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "Estat",
   "topicId": null,
   "assuntoLivre": "Amostragem Estratificada",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~amplitude-1e7ae7",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "Estat",
   "topicId": null,
   "assuntoLivre": "Amplitude",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~conceitos-basicos-e-definicoes-de-amostragem-em-estatistica-c777ce",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "Estat",
   "topicId": null,
   "assuntoLivre": "Conceitos básicos e definições de Amostragem em Estatística",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~da-responsabilizacao-administrativa-arts-6-e-7-da-lei-n-12-8-3590d1",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DAD",
   "topicId": null,
   "assuntoLivre": "Da Responsabilização Administrativa (arts. 6º e 7º da Lei nº 12.846/2013)",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~das-atribuicoes-do-presidente-da-republica-art-84-da-cf-1988-42abca",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Das Atribuições do Presidente da República (art. 84 da CF/1988)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~decreto-n-11-129-2022-regulamenta-a-lei-n-12-846-2013-lei-an-4c8c66",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DAD",
   "topicId": null,
   "assuntoLivre": "Decreto nº 11.129/2022 - Regulamenta a Lei nº 12.846/2013 (Lei Anticorrupção)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~decreto-n-11-462-2023-sistema-de-registro-de-precos-srp-e5c1b8",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DAD",
   "topicId": null,
   "assuntoLivre": "Decreto nº 11.462/2023 - Sistema de Registro de Preços (SRP)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~demonstracao-das-mutacoes-do-patrimonio-liquido-afo-e-cpu-794c40",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Demonstração das Mutações do Patrimônio Líquido (AFO e CPU)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~desvio-padrao-e-variancia-245a54",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "Estat",
   "topicId": null,
   "assuntoLivre": "Desvio Padrão e Variância",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~direitos-coletivos-dos-trabalhadores-arts-8-a-11-da-cf-1988-a57fc2",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Direitos Coletivos dos Trabalhadores (arts. 8º a 11 da CF/1988)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~direitos-sociais-e-dos-trabalhadores-arts-6-e-7-da-cf-1988-818cc3",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Direitos Sociais e dos Trabalhadores (arts. 6º e 7º da CF/1988)",
   "minutos": 1,
   "qResolvidas": 5,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~do-acordo-de-leniencia-arts-16-e-17-da-lei-n-12-846-2013-6ea3eb",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DAD",
   "topicId": null,
   "assuntoLivre": "Do Acordo de Leniência (arts. 16 e 17 da Lei nº 12.846/2013)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~do-estatuto-da-magistratura-art-93-da-cf-1988-a72e9a",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Do Estatuto da Magistratura (art. 93 da CF/1988)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~dos-atos-lesivos-a-administracao-publica-nacional-ou-estrang-582d7b",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DAD",
   "topicId": null,
   "assuntoLivre": "Dos Atos Lesivos à Administração Pública Nacional ou Estrangeira (art. 5º da Lei nº 12.846/2013)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~dos-direitos-e-deveres-individuais-e-coletivos-art-5-da-cf-1-f98ec8",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Dos Direitos e Deveres Individuais e Coletivos (art. 5º da CF/1988)",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~intervalo-interquartilico-e569ee",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "Estat",
   "topicId": null,
   "assuntoLivre": "Intervalo Interquartílico",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~peculato-art-312-do-cp-463c67",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "PENAL",
   "topicId": null,
   "assuntoLivre": "Peculato (art. 312 do CP)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~perda-e-suspensao-dos-direitos-politicos-0568d8",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Perda e Suspensão dos Direitos Políticos",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~propriedades-das-medidas-de-dispersao-67e6bb",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "Estat",
   "topicId": null,
   "assuntoLivre": "Propriedades das Medidas de Dispersão",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~propriedades-das-medidas-de-posicao-associadas-a-desvios-323789",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "Estat",
   "topicId": null,
   "assuntoLivre": "Propriedades das Medidas de Posição Associadas a Desvios",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~questoes-mescladas-de-medidas-de-posicao-f44dc2",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "Estat",
   "topicId": null,
   "assuntoLivre": "Questões Mescladas de Medidas de Posição",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~questoes-mescladas-de-poder-judiciario-arts-92-a-126-da-cf-1-a57628",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Questões Mescladas de Poder Judiciário (arts. 92 a 126 da CF/1988)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~questoes-mescladas-sobre-crimes-praticados-por-funcionario-p-2351bf",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "PENAL",
   "topicId": null,
   "assuntoLivre": "Questões Mescladas sobre Crimes Praticados por Funcionário Público contra a Administração em Geral (arts. 312 a 327 do CP)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-08~conceitos-de-bpm-gerenciamento-de-processos-de-negocio-cc89c3",
   "origem": "tec",
   "data": "2026-09-08",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Conceitos de BPM (Gerenciamento de Processos de Negócio)",
   "minutos": 24,
   "qResolvidas": 20,
   "qAcertadas": 18,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-08~imposto-sobre-bens-e-servicos-ibs-cf-1988-ec-132-21b555",
   "origem": "tec",
   "data": "2026-09-08",
   "mat": "TRIB",
   "topicId": null,
   "assuntoLivre": "Imposto sobre Bens e Serviços - IBS (CF/1988, EC 132)",
   "minutos": 17,
   "qResolvidas": 22,
   "qAcertadas": 20,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-09~da-base-de-calculo-arts-12-e-13-da-lc-n-214-2025-fac2eb",
   "origem": "tec",
   "data": "2026-09-09",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Da Base de Cálculo (arts. 12 e 13 da LC nº 214/2025)",
   "minutos": 29,
   "qResolvidas": 6,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-09~das-hipoteses-de-incidencia-arts-4-a-7-da-lc-n-214-2025-39b86f",
   "origem": "tec",
   "data": "2026-09-09",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Das Hipóteses de Incidência (arts. 4º a 7º da LC nº 214/2025)",
   "minutos": 4,
   "qResolvidas": 5,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-09~disposicoes-preliminares-arts-1-a-3-da-lc-n-214-2025-087e8f",
   "origem": "tec",
   "data": "2026-09-09",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Disposições Preliminares (arts. 1º a 3º da LC nº 214/2025)",
   "minutos": 15,
   "qResolvidas": 4,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-09~do-local-da-operacao-art-11-da-lc-n-214-2025-a7263a",
   "origem": "tec",
   "data": "2026-09-09",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Do Local da Operação (art. 11 da LC nº 214/2025)",
   "minutos": 5,
   "qResolvidas": 4,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-09~do-momento-de-ocorrencia-do-fato-gerador-art-10-da-lc-n-214--1a0ae1",
   "origem": "tec",
   "data": "2026-09-09",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "Do Momento de Ocorrência do Fato Gerador (art. 10 da LC nº 214/2025)",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-09~scrum-399530",
   "origem": "tec",
   "data": "2026-09-09",
   "mat": "DFin",
   "topicId": null,
   "assuntoLivre": "SCRUM",
   "minutos": 15,
   "qResolvidas": 36,
   "qAcertadas": 18,
   "obs": "reconstruída do TEC"
  }
 ]
};
