// Gerado por 06_Scripts/gerar_sessoes_tec.py - NAO editar a mao.
window.SESSOES_TEC = {
 "gerado_em": "2026-09-24T09:36:31",
 "fonte": "07_TEC/TEC_Captura/tec_registros_*.json (1 sessão por dia+assunto) + resultado_simulado_*.json (1 sessão por simulado+dia+matéria)",
 "sessoes": [
  {
   "uid": "TEC~2026-09-02~217",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "CGER",
   "topicId": "217",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~253",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "FINPUB",
   "topicId": "253",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~290",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "FINPUB",
   "topicId": "290",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~292",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "FINPUB",
   "topicId": "292",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~324",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "CPUB",
   "topicId": "324",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~332",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "CPUB",
   "topicId": "332",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~443",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "CGER",
   "topicId": "443",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~447",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "CGER",
   "topicId": "447",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~455",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "MATFIN",
   "topicId": "455",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~458",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "MATFIN",
   "topicId": "458",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 3,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~78",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DTRIB",
   "topicId": "78",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~82",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DTRIB",
   "topicId": "82",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 5,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-09-02~83",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DTRIB",
   "topicId": "83",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 4,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC (4 assuntos)"
  },
  {
   "uid": "TEC~2026-09-02~88",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DTRIB",
   "topicId": "88",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-09-02~89",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DTRIB",
   "topicId": "89",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 4,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~90",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DTRIB",
   "topicId": "90",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~93",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "DTRIB",
   "topicId": "93",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~classificacao-e-subsistemas-do-sfn-75036b",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "FINPUB",
   "topicId": null,
   "assuntoLivre": "Classificação e Subsistemas do SFN",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~composicao-geral-do-sfn-294b51",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "FINPUB",
   "topicId": null,
   "assuntoLivre": "Composição Geral do SFN",
   "minutos": 1,
   "qResolvidas": 3,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~demais-temas-sobre-custos-no-setor-publico-6ab4a8",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "CPUB",
   "topicId": null,
   "assuntoLivre": "Demais Temas sobre Custos no Setor Público",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-02~escrituracao-normas-livros-contabeis-lancamentos-metodo-das--2a030a",
   "origem": "tec",
   "data": "2026-09-02",
   "mat": "CGER",
   "topicId": null,
   "assuntoLivre": "Escrituração: Normas, Livros Contábeis, Lançamentos, Método das Partidas Dobradas",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~340",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "ESTAT",
   "topicId": "340",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~347",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "ESTAT",
   "topicId": "347",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~349",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "ESTAT",
   "topicId": "349",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~351",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "ESTAT",
   "topicId": "351",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~352",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "ESTAT",
   "topicId": "352",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~354",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DCON",
   "topicId": "354",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~369",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DCON",
   "topicId": "369",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~374",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DCON",
   "topicId": "374",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~381",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DCON",
   "topicId": "381",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 5,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~amplitude-1e7ae7",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "ESTAT",
   "topicId": null,
   "assuntoLivre": "Amplitude",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~atributos-ou-caracteristicas-dos-atos-administrativos-2fd71f",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DADM",
   "topicId": null,
   "assuntoLivre": "Atributos ou Características dos Atos Administrativos",
   "minutos": 1,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~da-responsabilizacao-administrativa-arts-6-e-7-da-lei-n-12-8-3590d1",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DADM",
   "topicId": null,
   "assuntoLivre": "Da Responsabilização Administrativa (arts. 6º e 7º da Lei nº 12.846/2013)",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~decreto-n-11-129-2022-regulamenta-a-lei-n-12-846-2013-lei-an-4c8c66",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DADM",
   "topicId": null,
   "assuntoLivre": "Decreto nº 11.129/2022 - Regulamenta a Lei nº 12.846/2013 (Lei Anticorrupção)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~decreto-n-11-462-2023-sistema-de-registro-de-precos-srp-e5c1b8",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DADM",
   "topicId": null,
   "assuntoLivre": "Decreto nº 11.462/2023 - Sistema de Registro de Preços (SRP)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~demonstracao-das-mutacoes-do-patrimonio-liquido-afo-e-cpu-794c40",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "CPUB",
   "topicId": null,
   "assuntoLivre": "Demonstração das Mutações do Patrimônio Líquido (AFO e CPU)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~direitos-coletivos-dos-trabalhadores-arts-8-a-11-da-cf-1988-a57fc2",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Direitos Coletivos dos Trabalhadores (arts. 8º a 11 da CF/1988)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~do-acordo-de-leniencia-arts-16-e-17-da-lei-n-12-846-2013-6ea3eb",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DADM",
   "topicId": null,
   "assuntoLivre": "Do Acordo de Leniência (arts. 16 e 17 da Lei nº 12.846/2013)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~do-estatuto-da-magistratura-art-93-da-cf-1988-a72e9a",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Do Estatuto da Magistratura (art. 93 da CF/1988)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~dos-atos-lesivos-a-administracao-publica-nacional-ou-estrang-582d7b",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DADM",
   "topicId": null,
   "assuntoLivre": "Dos Atos Lesivos à Administração Pública Nacional ou Estrangeira (art. 5º da Lei nº 12.846/2013)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~intervalo-interquartilico-e569ee",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "ESTAT",
   "topicId": null,
   "assuntoLivre": "Intervalo Interquartílico",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~peculato-art-312-do-cp-463c67",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DTRIB",
   "topicId": null,
   "assuntoLivre": "Peculato (art. 312 do CP)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~propriedades-das-medidas-de-dispersao-67e6bb",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "ESTAT",
   "topicId": null,
   "assuntoLivre": "Propriedades das Medidas de Dispersão",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~propriedades-das-medidas-de-posicao-associadas-a-desvios-323789",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "ESTAT",
   "topicId": null,
   "assuntoLivre": "Propriedades das Medidas de Posição Associadas a Desvios",
   "minutos": 2,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~questoes-mescladas-de-poder-judiciario-arts-92-a-126-da-cf-1-a57628",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DCON",
   "topicId": null,
   "assuntoLivre": "Questões Mescladas de Poder Judiciário (arts. 92 a 126 da CF/1988)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-03~questoes-mescladas-sobre-crimes-praticados-por-funcionario-p-2351bf",
   "origem": "tec",
   "data": "2026-09-03",
   "mat": "DTRIB",
   "topicId": null,
   "assuntoLivre": "Questões Mescladas sobre Crimes Praticados por Funcionário Público contra a Administração em Geral (arts. 312 a 327 do CP)",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 0,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-08~1",
   "origem": "tec",
   "data": "2026-09-08",
   "mat": "RT",
   "topicId": "1",
   "assuntoLivre": "",
   "minutos": 16,
   "qResolvidas": 19,
   "qAcertadas": 17,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-08~55",
   "origem": "tec",
   "data": "2026-09-08",
   "mat": "DEV",
   "topicId": "55",
   "assuntoLivre": "",
   "minutos": 24,
   "qResolvidas": 20,
   "qAcertadas": 18,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-08~81",
   "origem": "tec",
   "data": "2026-09-08",
   "mat": "DTRIB",
   "topicId": "81",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-09~10",
   "origem": "tec",
   "data": "2026-09-09",
   "mat": "RT",
   "topicId": "10",
   "assuntoLivre": "",
   "minutos": 15,
   "qResolvidas": 4,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-09~11",
   "origem": "tec",
   "data": "2026-09-09",
   "mat": "RT",
   "topicId": "11",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 4,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-09~12",
   "origem": "tec",
   "data": "2026-09-09",
   "mat": "RT",
   "topicId": "12",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-09~49",
   "origem": "tec",
   "data": "2026-09-09",
   "mat": "DEV",
   "topicId": "49",
   "assuntoLivre": "",
   "minutos": 15,
   "qResolvidas": 36,
   "qAcertadas": 18,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-09~7",
   "origem": "tec",
   "data": "2026-09-09",
   "mat": "RT",
   "topicId": "7",
   "assuntoLivre": "",
   "minutos": 29,
   "qResolvidas": 6,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-09~8",
   "origem": "tec",
   "data": "2026-09-09",
   "mat": "RT",
   "topicId": "8",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 5,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-10~13",
   "origem": "tec",
   "data": "2026-09-10",
   "mat": "RT",
   "topicId": "13",
   "assuntoLivre": "",
   "minutos": 15,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-10~49",
   "origem": "tec",
   "data": "2026-09-10",
   "mat": "DEV",
   "topicId": "49",
   "assuntoLivre": "",
   "minutos": 18,
   "qResolvidas": 42,
   "qAcertadas": 31,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-10~9",
   "origem": "tec",
   "data": "2026-09-10",
   "mat": "RT",
   "topicId": "9",
   "assuntoLivre": "",
   "minutos": 6,
   "qResolvidas": 5,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-11~1",
   "origem": "tec",
   "data": "2026-09-11",
   "mat": "RT",
   "topicId": "1",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-11~12",
   "origem": "tec",
   "data": "2026-09-11",
   "mat": "RT",
   "topicId": "12",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-11~13",
   "origem": "tec",
   "data": "2026-09-11",
   "mat": "RT",
   "topicId": "13",
   "assuntoLivre": "",
   "minutos": 12,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-11~2",
   "origem": "tec",
   "data": "2026-09-11",
   "mat": "RT",
   "topicId": "2",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-11~3",
   "origem": "tec",
   "data": "2026-09-11",
   "mat": "RT",
   "topicId": "3",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-11~4",
   "origem": "tec",
   "data": "2026-09-11",
   "mat": "RT",
   "topicId": "4",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 3,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-11~56",
   "origem": "tec",
   "data": "2026-09-11",
   "mat": "DEV",
   "topicId": "56",
   "assuntoLivre": "",
   "minutos": 104,
   "qResolvidas": 17,
   "qAcertadas": 12,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-11~65",
   "origem": "tec",
   "data": "2026-09-11",
   "mat": "DEV",
   "topicId": "65",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 7,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-11~7",
   "origem": "tec",
   "data": "2026-09-11",
   "mat": "RT",
   "topicId": "7",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-11~8",
   "origem": "tec",
   "data": "2026-09-11",
   "mat": "RT",
   "topicId": "8",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-11~9",
   "origem": "tec",
   "data": "2026-09-11",
   "mat": "RT",
   "topicId": "9",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "SIM~RT02~2026-09-14~RT",
   "origem": "simulado",
   "data": "2026-09-14",
   "mat": "RT",
   "topicId": null,
   "assuntoLivre": "Simulado RT02 — RT",
   "minutos": 10,
   "qResolvidas": 30,
   "qAcertadas": 24,
   "obs": "Simulado RT02 (Q1-30) cronometrado"
  },
  {
   "uid": "TEC~2026-09-14~119",
   "origem": "tec",
   "data": "2026-09-14",
   "mat": "RT",
   "topicId": "119",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-14~30",
   "origem": "tec",
   "data": "2026-09-14",
   "mat": "INFRA",
   "topicId": "30",
   "assuntoLivre": "",
   "minutos": 9,
   "qResolvidas": 14,
   "qAcertadas": 12,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-14~33",
   "origem": "tec",
   "data": "2026-09-14",
   "mat": "INFRA",
   "topicId": "33",
   "assuntoLivre": "",
   "minutos": 15,
   "qResolvidas": 12,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-14~55",
   "origem": "tec",
   "data": "2026-09-14",
   "mat": "DEV",
   "topicId": "55",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 10,
   "qAcertadas": 9,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-09-14~81",
   "origem": "tec",
   "data": "2026-09-14",
   "mat": "DTRIB",
   "topicId": "81",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 6,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "SIM~RT03~2026-09-15~RT",
   "origem": "simulado",
   "data": "2026-09-15",
   "mat": "RT",
   "topicId": null,
   "assuntoLivre": "Simulado RT03 — RT",
   "minutos": 3,
   "qResolvidas": 9,
   "qAcertadas": 5,
   "obs": "Simulado RT03 (Q1-9) cronometrado"
  },
  {
   "uid": "SIM~RT04~2026-09-15~RT",
   "origem": "simulado",
   "data": "2026-09-15",
   "mat": "RT",
   "topicId": null,
   "assuntoLivre": "Simulado RT04 — RT",
   "minutos": 7,
   "qResolvidas": 34,
   "qAcertadas": 29,
   "obs": "Simulado RT04 (Q1-34) cronometrado"
  },
  {
   "uid": "TEC~2026-09-15~120",
   "origem": "tec",
   "data": "2026-09-15",
   "mat": "RT",
   "topicId": "120",
   "assuntoLivre": "",
   "minutos": 7,
   "qResolvidas": 5,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-15~30",
   "origem": "tec",
   "data": "2026-09-15",
   "mat": "INFRA",
   "topicId": "30",
   "assuntoLivre": "",
   "minutos": 8,
   "qResolvidas": 14,
   "qAcertadas": 13,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-15~33",
   "origem": "tec",
   "data": "2026-09-15",
   "mat": "INFRA",
   "topicId": "33",
   "assuntoLivre": "",
   "minutos": 8,
   "qResolvidas": 12,
   "qAcertadas": 11,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-15~49",
   "origem": "tec",
   "data": "2026-09-15",
   "mat": "DEV",
   "topicId": "49",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 13,
   "qAcertadas": 11,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-16~121",
   "origem": "tec",
   "data": "2026-09-16",
   "mat": "RT",
   "topicId": "121",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 2,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC (2 assuntos)"
  },
  {
   "uid": "TEC~2026-09-16~17",
   "origem": "tec",
   "data": "2026-09-16",
   "mat": "AUDFIS",
   "topicId": "17",
   "assuntoLivre": "",
   "minutos": 15,
   "qResolvidas": 13,
   "qAcertadas": 7,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-16~23",
   "origem": "tec",
   "data": "2026-09-16",
   "mat": "AUDFIS",
   "topicId": "23",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 6,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-16~28",
   "origem": "tec",
   "data": "2026-09-16",
   "mat": "INFRA",
   "topicId": "28",
   "assuntoLivre": "",
   "minutos": 12,
   "qResolvidas": 33,
   "qAcertadas": 27,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-16~81",
   "origem": "tec",
   "data": "2026-09-16",
   "mat": "DTRIB",
   "topicId": "81",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "SIM~RT06~2026-09-17~RT",
   "origem": "simulado",
   "data": "2026-09-17",
   "mat": "RT",
   "topicId": null,
   "assuntoLivre": "Simulado RT06 — RT",
   "minutos": 5,
   "qResolvidas": 20,
   "qAcertadas": 18,
   "obs": "Simulado RT06 (Q1-20) cronometrado"
  },
  {
   "uid": "TEC~2026-09-17~122",
   "origem": "tec",
   "data": "2026-09-17",
   "mat": "RT",
   "topicId": "122",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 1,
   "qAcertadas": 1,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-17~22",
   "origem": "tec",
   "data": "2026-09-17",
   "mat": "AUDFIS",
   "topicId": "22",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 5,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-17~237",
   "origem": "tec",
   "data": "2026-09-17",
   "mat": "IA",
   "topicId": "237",
   "assuntoLivre": "",
   "minutos": 32,
   "qResolvidas": 47,
   "qAcertadas": 45,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-17~28",
   "origem": "tec",
   "data": "2026-09-17",
   "mat": "INFRA",
   "topicId": "28",
   "assuntoLivre": "",
   "minutos": 11,
   "qResolvidas": 29,
   "qAcertadas": 23,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-18~2",
   "origem": "tec",
   "data": "2026-09-18",
   "mat": "RT",
   "topicId": "2",
   "assuntoLivre": "",
   "minutos": 10,
   "qResolvidas": 15,
   "qAcertadas": 14,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-18~3",
   "origem": "tec",
   "data": "2026-09-18",
   "mat": "RT",
   "topicId": "3",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 6,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-18~32",
   "origem": "tec",
   "data": "2026-09-18",
   "mat": "INFRA",
   "topicId": "32",
   "assuntoLivre": "",
   "minutos": 5,
   "qResolvidas": 16,
   "qAcertadas": 12,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-18~36",
   "origem": "tec",
   "data": "2026-09-18",
   "mat": "INFRA",
   "topicId": "36",
   "assuntoLivre": "",
   "minutos": 7,
   "qResolvidas": 14,
   "qAcertadas": 10,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-18~4",
   "origem": "tec",
   "data": "2026-09-18",
   "mat": "RT",
   "topicId": "4",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 5,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-18~44",
   "origem": "tec",
   "data": "2026-09-18",
   "mat": "INFRA",
   "topicId": "44",
   "assuntoLivre": "",
   "minutos": 55,
   "qResolvidas": 6,
   "qAcertadas": 4,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-18~56",
   "origem": "tec",
   "data": "2026-09-18",
   "mat": "DEV",
   "topicId": "56",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 7,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-18~65",
   "origem": "tec",
   "data": "2026-09-18",
   "mat": "DEV",
   "topicId": "65",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-18~81",
   "origem": "tec",
   "data": "2026-09-18",
   "mat": "DTRIB",
   "topicId": "81",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 5,
   "qAcertadas": 5,
   "obs": "reconstruída do TEC (3 assuntos)"
  },
  {
   "uid": "TEC~2026-09-21~das-competencias-do-cgibs-e-das-diretrizes-para-a-coordenaca-5e512b",
   "origem": "tec",
   "data": "2026-09-21",
   "mat": "RT",
   "topicId": null,
   "assuntoLivre": "Das Competências do CGIBS e das Diretrizes para a Coordenação da Fiscalização e da Cobrança do IBS (arts. 2º a 6º da LC nº 227/2026)",
   "minutos": 2,
   "qResolvidas": 2,
   "qAcertadas": 2,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-22~226",
   "origem": "tec",
   "data": "2026-09-22",
   "mat": "CDADOS",
   "topicId": "226",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 3,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-22~230",
   "origem": "tec",
   "data": "2026-09-22",
   "mat": "CDADOS",
   "topicId": "230",
   "assuntoLivre": "",
   "minutos": 4,
   "qResolvidas": 14,
   "qAcertadas": 14,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-22~232",
   "origem": "tec",
   "data": "2026-09-22",
   "mat": "CDADOS",
   "topicId": "232",
   "assuntoLivre": "",
   "minutos": 2,
   "qResolvidas": 10,
   "qAcertadas": 10,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-22~233",
   "origem": "tec",
   "data": "2026-09-22",
   "mat": "CDADOS",
   "topicId": "233",
   "assuntoLivre": "",
   "minutos": 3,
   "qResolvidas": 9,
   "qAcertadas": 6,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-22~237",
   "origem": "tec",
   "data": "2026-09-22",
   "mat": "IA",
   "topicId": "237",
   "assuntoLivre": "",
   "minutos": 1,
   "qResolvidas": 4,
   "qAcertadas": 3,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "TEC~2026-09-22~50",
   "origem": "tec",
   "data": "2026-09-22",
   "mat": "DEV",
   "topicId": "50",
   "assuntoLivre": "",
   "minutos": 18,
   "qResolvidas": 42,
   "qAcertadas": 29,
   "obs": "reconstruída do TEC"
  },
  {
   "uid": "SIM~RT07~2026-09-23~RT",
   "origem": "simulado",
   "data": "2026-09-23",
   "mat": "RT",
   "topicId": null,
   "assuntoLivre": "Simulado RT07 — RT",
   "minutos": 6,
   "qResolvidas": 30,
   "qAcertadas": 22,
   "obs": "Simulado RT07 (Q1-30) cronometrado"
  }
 ]
};
